[package]
name = "stirlings"
version = "0.1"
lean_version = "leanprover-community/lean:3.43.0"
path = "src"

[dependencies]
mathlib = {git = "https://github.com/leanprover-community/mathlib", rev = "d939b0e6a6ede5bf84d45e10be5c7f9dd927841b"}
